In [2]:
import numpy as np 
print(np.__version__)

1.18.5


In [11]:
#1. Write a Python program to reverse an array
#(first element becomes last).

arr1= np.arange(1,11)
arr1=arr1[::-1]
print(arr1)

[10  9  8  7  6  5  4  3  2  1]


In [13]:
#Write a Python program to convert a list and
#tuple into arrays.
arr1= np.arange(1,11)
list1=list(arr1)
tuple1=tuple(arr1)
print(list1)
print(tuple1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)


In [14]:
#Write a Python program to find common values
#between two arrays.
arr1=np.arange(1,11)
arr2=np.arange(5,16)
print(np.intersect1d(arr1, arr2))

[ 5  6  7  8  9 10]


In [15]:
arr1 = np.array([1, 2])
arr2 = np.array([4, 5])
print("Array a: ",arr1)
print("Array b: ",arr2)
print("a > b")
print(np.greater(arr1, arr2))
print("a >= b")
print(np.greater_equal(a, b))
print("a < b")
print(np.less(a, b))
print("a <= b")
print(np.less_equal(a, b))

Array a:  [1 2]
Array b:  [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


In [8]:
# Write a Python program to change the
# dimension of an array.
arr1=np.arange(1,11)
print(arr1)
arr1.shape=(2,5)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
#Write a Python program (using numpy) to sum of all the multiples of 3 or 5 below 100.
sum=0
for i in range(1,100):
    if(i%3==0 or i%5==0):
        sum=sum+i
print(sum)

2318


In [13]:
# Write a Python program to convert a NumPy
# array into Python list structure.
arr1=np.arange(1,11).reshape(2,5)
print(arr1.tolist())

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


In [24]:
# Write a Python program to how to add an extra
# column to a numpy array.
arr1=np.arange(1,11).reshape(2,5)
arr2=np.arange(11,21).reshape(2,5)
arr3=np.append(arr1,arr2,axis=1)
print(arr3)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [30]:
# Write a Python program to check whether the
# numpy array is empty or not.
arr1=np.array([])
if (len(arr1)==0):
    print("Array is empty")
else:
    print("Array is not empty")

Array is not empty


In [31]:
#Write a Python program to normalize a 3x3
# random matrix.
x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.95728497 0.39809913 0.74799253]
 [0.80531749 0.57828202 0.55726225]
 [0.43571537 0.30195551 0.67534979]]
After normalization:
[[1.         0.14671037 0.6806302 ]
 [0.76810522 0.42166044 0.38958533]
 [0.20411087 0.         0.56978102]]


In [43]:
# How to swap two rows of an array?
arr1=np.arange(1,13).reshape(4,3)
print(arr1)
arr1[[2,1]]=arr1[[1,2]]
print(arr1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [10 11 12]]


In [52]:
# Write a Python program to check two random arrays are equal or not.
arr1=np.array([2,4,6,8,9,7,5,3,1])
arr2=np.array([9,7,5,3,1,2,4,6])
flag=True
if len(arr1)==len(arr2):
    arr1.sort()
    arr2.sort()
    for i in range(0,len(arr1)):
        if(arr1[i]!=arr2[i]):
            flag=False
else:
    flag=False
if flag:
    print("Equal")
else:
    print("Not Equal")

Not Equal


In [59]:
# Write a Python program to add, subtract,multiply, divide arguments element-wise.
print("Add:")
print(np.add(10, 1))
print("Subtract:")
print(np.subtract(10, 1))
print("Multiply:")
print(np.multiply(10, 1))
print("Divide:")
print(np.divide(10, 1))

Add:
11
Subtract:
9
Multiply:
10
Divide:
10.0


In [65]:
# Write a Python program to get the dates of yesterday, today and tomorrow.
import datetime 
today = datetime.date.today()
yesterday = today - datetime.timedelta(days = 1)
tomorrow = today + datetime.timedelta(days = 1) 
print('Yesterday : ',yesterday)
print('Today : ',today)
print('Tomorrow : ',tomorrow)

Yesterday :  2020-11-29
Today :  2020-11-30
Tomorrow :  2020-12-01
