# Broadcastable Array

In [3]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(arr1+arr2)

[ 6  8 10 12]


In [4]:
arr1 = np.arange(1,13).reshape(4,3)
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
arr2 = np.arange(22,25).reshape(1,3)
arr2

array([[22, 23, 24]])

In [6]:
arr1 + arr2

array([[23, 25, 27],
       [26, 28, 30],
       [29, 31, 33],
       [32, 34, 36]])

In [ ]:
# An array can be broadcastable -
1. if no of rows of both the array are equal and any one array has no of columns = 1
2. if no of columns of both the arrays are equal and any one array has no of rows = 1

In [ ]:
arr1 = 3X5
arr2 = 3X1

In [ ]:
arr1 = 5X1
arr2 = 5X3

In [7]:
arr1 = np.arange(1,6).reshape(5,1)
arr1

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [8]:
arr2 = np.arange(15,30).reshape(5,3)
arr2

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [9]:
arr1 + arr2

array([[16, 17, 18],
       [20, 21, 22],
       [24, 25, 26],
       [28, 29, 30],
       [32, 33, 34]])

In [13]:
arr1 = np.array([[1,2,3,4,5]])

arr1.shape

(1, 5)

In [16]:
arr2 = np.arange(11,16).reshape(5,1)
arr2


array([[11],
       [12],
       [13],
       [14],
       [15]])

In [15]:
arr1 + arr2

array([[12, 13, 14, 15, 16],
       [13, 14, 15, 16, 17],
       [14, 15, 16, 17, 18],
       [15, 16, 17, 18, 19],
       [16, 17, 18, 19, 20]])

In [ ]:
[1,2,3,4,5]                 [[11 11 11 11 11],
[1,2,3,4,5]                  [12 12 12 12 12],
[1,2,3,4,5]                  [13 13 13 13 13],
[1,2,3,4,5]                  [14 14 14 14 14],
[1,2,3,4,5]                  [15 15 15 15 15]]

In [17]:
arr1 = np.arange(2,12).reshape(5,2)
arr1

array([[ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [19]:
arr2 = np.arange(25,55).reshape(5,6)
arr2

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54]])

In [20]:
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (5,2) (5,6) 

# Itertion over an array

In [21]:
import numpy as np

In [22]:
arr1 = np.arange(25,55)
arr1

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54])

In [23]:
for i in arr1:
    print(i)

25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54


In [24]:
arr2 = arr1.reshape(5,6)
arr2

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54]])

In [26]:
for i in arr2:
    for j in i:
        print(j)

25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54


In [27]:
for i in arr2.flatten():
    print(i)


25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54


In [30]:
arr2

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54]])

In [28]:
for i in np.nditer(arr2, order = 'C'):   # Row major form
    print(i)

25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54


In [32]:
arr2[2,1]

38

In [29]:
for i in np.nditer(arr2, order = 'F'):   # Column majotr form
    print(i)

25
31
37
43
49
26
32
38
44
50
27
33
39
45
51
28
34
40
46
52
29
35
41
47
53
30
36
42
48
54


# Splitting an array

In [33]:
import numpy as np

In [34]:
arr1 = np.arange(25, 61).reshape(6,6)
arr1

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [42]:
# Splitting an array in 3 equal parts
np.split(arr1, 3)

[array([[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]]), array([[37, 38, 39, 40, 41, 42],
        [43, 44, 45, 46, 47, 48]]), array([[49, 50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59, 60]])]

In [44]:
np.split(arr1, [1,3, 4])

[array([[25, 26, 27, 28, 29, 30]]), array([[31, 32, 33, 34, 35, 36],
        [37, 38, 39, 40, 41, 42]]), array([[43, 44, 45, 46, 47, 48]]), array([[49, 50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59, 60]])]

In [47]:
arr1

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [46]:
np.hsplit(arr1, 3)

[array([[25, 26],
        [31, 32],
        [37, 38],
        [43, 44],
        [49, 50],
        [55, 56]]), array([[27, 28],
        [33, 34],
        [39, 40],
        [45, 46],
        [51, 52],
        [57, 58]]), array([[29, 30],
        [35, 36],
        [41, 42],
        [47, 48],
        [53, 54],
        [59, 60]])]

# Stacking = concatenation

In [55]:
arr1 = np.array([1,2,3,4,6]).reshape(1,5)
arr1

array([[1, 2, 3, 4, 6]])

In [56]:
arr2 = np.array([9,8,7,6,5]).reshape(1,5)
arr2

array([[9, 8, 7, 6, 5]])

In [60]:
np.concatenate((arr1,arr2))

array([[1, 2, 3, 4, 6],
       [9, 8, 7, 6, 5]])

In [59]:
np.concatenate((arr1,arr2), axis = 1)

array([[1, 2, 3, 4, 6, 9, 8, 7, 6, 5]])

In [61]:
np.concatenate([arr1,arr2], axis = 0)

array([[1, 2, 3, 4, 6],
       [9, 8, 7, 6, 5]])

# view and copy

view = aliasing

In [71]:
arr1 = np.arange(5,15).reshape(5,2)
arr1

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [77]:
v1 = arr1[::, ::]
v1

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [78]:
v1[1][0] = 777
v1

array([[  5,   6],
       [777,   8],
       [  9,  10],
       [ 11,  12],
       [ 13,  14]])

In [79]:
arr1

array([[  5,   6],
       [777,   8],
       [  9,  10],
       [ 11,  12],
       [ 13,  14]])

copy = deepcopy

In [73]:
# Creating a deepcopy of array
c1 = np.copy(arr1)
c1

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [75]:
c1[1,0] = 777
c1

array([[  5,   6],
       [777,   8],
       [  9,  10],
       [ 11,  12],
       [ 13,  14]])

In [76]:
arr1

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])