# Numpy

In [ ]:
Numpy - Numerical Python
Computation and processing of 1D or nD array.
Any data can be easily represented in the form of array.
Array related operation are important to know for Numpy Operation
Numpy provides the efficient storage and efficient operations related to Numpy Array.

In [5]:
import array
arr = array.array('i',[10,20,30])
arr

array('i', [10, 20, 30])

In [ ]:
lst = [10,20,30]


In [20]:
# With resect to storage
lst = list(range(100000))
# print(lst, type(lst))




In [23]:
import numpy as np
arr = np.array(lst)
print(arr, type(arr))
arr

[    0     1     2 ... 99997 99998 99999] <class 'numpy.ndarray'>


array([    0,     1,     2, ..., 99997, 99998, 99999])

In [48]:
# With respect to operation
# print(lst*2)

[i*2 for i in lst]

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [38]:
arr * 2

array([     0,      2,      4, ..., 199994, 199996, 199998])

In [49]:
import numpy as np

In [ ]:
# !pip install numpy

In [51]:
# Creating Numpy Array from List
lst = [10,20,30]
arr = np.array(lst)
print(arr)
print(arr.dtype)

[10 20 30]
int64


In [52]:
lst = [10,20,30.40]
arr = np.array(lst)
print(arr, arr.dtype)

[10.  20.  30.4] float64


In [ ]:
# int, float, complex, object

In [53]:
lst = [10,20,30.40, 50+60j]
arr = np.array(lst)
print(arr, arr.dtype)

[10.  +0.j 20.  +0.j 30.4 +0.j 50. +60.j] complex128


In [54]:
lst = [10,20,30.40, 50+60j, 'a']
arr = np.array(lst)
print(arr, arr.dtype)

['10' '20' '30.4' '(50+60j)' 'a'] <U64


In [55]:
# size = number of elemnts in the array
print(arr.size)

5


In [57]:
# shape - returns the no of rows and columns of an array
print(arr.shape)

(5,)


In [56]:
import sys
sys.getsizeof(arr)

1376

In [61]:
# Creating a 2D array
arr1 = np.array([[1,2,3, 4], [4,5,6, 7],[7,8,9,10]])
print(arr1.shape)

(3, 4)


In [62]:
arr1.ndim

2

In [63]:
arr.ndim

1

In [65]:
np.array([
    [[1,2,3,4],[5,6,7,8],[9,8,7,6]],
    [[10,11,12,13],[14,15,16,17],[18,19,20,21]],
    [[22,23,24,25],[26,27,28,29],[30,31,32,33]]
]).ndim

3

In [67]:
np.array([
    [[1,2,3,4],[5,6,7,8],[9,8,7,6]],
    [[10,11,12,13],[14,15,16,17],[18,19,20,21]],
    [[22,23,24,25],[26,27,28,29],[30,31,32,33]],
    [[22,23,24,25],[26,27,28,29],[30,31,32,33]]
]).shape

(4, 3, 4)

In [68]:
# Creating an array using arange function
# np.arange(start, stop, step)
# np.arange(stop)

np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
np.arange(11, 21, 1)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [72]:
np.arange(11, 21, 0.5)

array([11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5])

In [74]:
np.arange(11, 15, 0.002)

2000

In [81]:
# Creating an array using linspace
# np.linspace(11, 20)

array([11.        , 11.18367347, 11.36734694, 11.55102041, 11.73469388,
       11.91836735, 12.10204082, 12.28571429, 12.46938776, 12.65306122,
       12.83673469, 13.02040816, 13.20408163, 13.3877551 , 13.57142857,
       13.75510204, 13.93877551, 14.12244898, 14.30612245, 14.48979592,
       14.67346939, 14.85714286, 15.04081633, 15.2244898 , 15.40816327,
       15.59183673, 15.7755102 , 15.95918367, 16.14285714, 16.32653061,
       16.51020408, 16.69387755, 16.87755102, 17.06122449, 17.24489796,
       17.42857143, 17.6122449 , 17.79591837, 17.97959184, 18.16326531,
       18.34693878, 18.53061224, 18.71428571, 18.89795918, 19.08163265,
       19.26530612, 19.44897959, 19.63265306, 19.81632653, 20.        ])

In [82]:
# np.linspace(31, 40)

array([31.        , 31.18367347, 31.36734694, 31.55102041, 31.73469388,
       31.91836735, 32.10204082, 32.28571429, 32.46938776, 32.65306122,
       32.83673469, 33.02040816, 33.20408163, 33.3877551 , 33.57142857,
       33.75510204, 33.93877551, 34.12244898, 34.30612245, 34.48979592,
       34.67346939, 34.85714286, 35.04081633, 35.2244898 , 35.40816327,
       35.59183673, 35.7755102 , 35.95918367, 36.14285714, 36.32653061,
       36.51020408, 36.69387755, 36.87755102, 37.06122449, 37.24489796,
       37.42857143, 37.6122449 , 37.79591837, 37.97959184, 38.16326531,
       38.34693878, 38.53061224, 38.71428571, 38.89795918, 39.08163265,
       39.26530612, 39.44897959, 39.63265306, 39.81632653, 40.        ])

In [92]:
# Creating a multidimensional array using arange
arr2 = np.arange(11, 15, 0.002).reshape(10,20,10)
arr2

array([[[11.   , 11.002, 11.004, ..., 11.014, 11.016, 11.018],
        [11.02 , 11.022, 11.024, ..., 11.034, 11.036, 11.038],
        [11.04 , 11.042, 11.044, ..., 11.054, 11.056, 11.058],
        ...,
        [11.34 , 11.342, 11.344, ..., 11.354, 11.356, 11.358],
        [11.36 , 11.362, 11.364, ..., 11.374, 11.376, 11.378],
        [11.38 , 11.382, 11.384, ..., 11.394, 11.396, 11.398]],

       [[11.4  , 11.402, 11.404, ..., 11.414, 11.416, 11.418],
        [11.42 , 11.422, 11.424, ..., 11.434, 11.436, 11.438],
        [11.44 , 11.442, 11.444, ..., 11.454, 11.456, 11.458],
        ...,
        [11.74 , 11.742, 11.744, ..., 11.754, 11.756, 11.758],
        [11.76 , 11.762, 11.764, ..., 11.774, 11.776, 11.778],
        [11.78 , 11.782, 11.784, ..., 11.794, 11.796, 11.798]],

       [[11.8  , 11.802, 11.804, ..., 11.814, 11.816, 11.818],
        [11.82 , 11.822, 11.824, ..., 11.834, 11.836, 11.838],
        [11.84 , 11.842, 11.844, ..., 11.854, 11.856, 11.858],
        ...,
        [12.

In [97]:
arr = np.zeros((4,5), dtype = 'int')
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [93]:
np.zeros_like([[1,2,3,4],[5,6,7,8]])

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [96]:
np.zeros_like([1,2,3,4,5,6,7,8.9])

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [99]:
np.ones((5,4), dtype = 'int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [100]:
np.ones_like([1,2,3,4,5,6,7,8.9])

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [108]:
np.empty((3,4), dtype = 'int')

array([[4599427227168655194, 4601430541013511554, 4593834980868997824,
        4599497578483082700],
       [4598348888393676232, 4603370121173050345, 4603376933258738605,
        4604757973483575589],
       [4598124196089165648, 4603059032381055918, 4587442921291402992,
        4604621764747315481]])

In [106]:
np.random.rand(3,4)

array([[0.31950038, 0.43070664, 0.12953418, 0.32340567],
       [0.25964056, 0.57674994, 0.57750623, 0.7308325 ],
       [0.24858381, 0.54221215, 0.05052972, 0.71571029]])

# Printing the array

In [109]:
arr = np.array([10,20,30])
arr

array([10, 20, 30])

In [110]:
print(arr)

[10 20 30]


In [111]:
print(np.random.rand(3,4))

[[0.56442233 0.83956932 0.42501401 0.06090811]
 [0.03771889 0.4298706  0.86463432 0.42372239]
 [0.42239384 0.46879221 0.53067291 0.09806656]]


In [113]:
arr2 = np.arange(11, 15, 0.002).reshape(50,40)
arr2

array([[11.   , 11.002, 11.004, ..., 11.074, 11.076, 11.078],
       [11.08 , 11.082, 11.084, ..., 11.154, 11.156, 11.158],
       [11.16 , 11.162, 11.164, ..., 11.234, 11.236, 11.238],
       ...,
       [14.76 , 14.762, 14.764, ..., 14.834, 14.836, 14.838],
       [14.84 , 14.842, 14.844, ..., 14.914, 14.916, 14.918],
       [14.92 , 14.922, 14.924, ..., 14.994, 14.996, 14.998]])

In [114]:
import sys
np.set_printoptions(threshold=sys.maxsize)

In [115]:
arr2

array([[11.   , 11.002, 11.004, 11.006, 11.008, 11.01 , 11.012, 11.014,
        11.016, 11.018, 11.02 , 11.022, 11.024, 11.026, 11.028, 11.03 ,
        11.032, 11.034, 11.036, 11.038, 11.04 , 11.042, 11.044, 11.046,
        11.048, 11.05 , 11.052, 11.054, 11.056, 11.058, 11.06 , 11.062,
        11.064, 11.066, 11.068, 11.07 , 11.072, 11.074, 11.076, 11.078],
       [11.08 , 11.082, 11.084, 11.086, 11.088, 11.09 , 11.092, 11.094,
        11.096, 11.098, 11.1  , 11.102, 11.104, 11.106, 11.108, 11.11 ,
        11.112, 11.114, 11.116, 11.118, 11.12 , 11.122, 11.124, 11.126,
        11.128, 11.13 , 11.132, 11.134, 11.136, 11.138, 11.14 , 11.142,
        11.144, 11.146, 11.148, 11.15 , 11.152, 11.154, 11.156, 11.158],
       [11.16 , 11.162, 11.164, 11.166, 11.168, 11.17 , 11.172, 11.174,
        11.176, 11.178, 11.18 , 11.182, 11.184, 11.186, 11.188, 11.19 ,
        11.192, 11.194, 11.196, 11.198, 11.2  , 11.202, 11.204, 11.206,
        11.208, 11.21 , 11.212, 11.214, 11.216, 11.218, 11.22 

In [133]:
# Reshaping an array
arr1 = np.arange(11,20,0.05)
print(arr1.size)

arr2 = arr1.reshape(12,-1)
arr2

180


array([[11.  , 11.05, 11.1 , 11.15, 11.2 , 11.25, 11.3 , 11.35, 11.4 ,
        11.45, 11.5 , 11.55, 11.6 , 11.65, 11.7 ],
       [11.75, 11.8 , 11.85, 11.9 , 11.95, 12.  , 12.05, 12.1 , 12.15,
        12.2 , 12.25, 12.3 , 12.35, 12.4 , 12.45],
       [12.5 , 12.55, 12.6 , 12.65, 12.7 , 12.75, 12.8 , 12.85, 12.9 ,
        12.95, 13.  , 13.05, 13.1 , 13.15, 13.2 ],
       [13.25, 13.3 , 13.35, 13.4 , 13.45, 13.5 , 13.55, 13.6 , 13.65,
        13.7 , 13.75, 13.8 , 13.85, 13.9 , 13.95],
       [14.  , 14.05, 14.1 , 14.15, 14.2 , 14.25, 14.3 , 14.35, 14.4 ,
        14.45, 14.5 , 14.55, 14.6 , 14.65, 14.7 ],
       [14.75, 14.8 , 14.85, 14.9 , 14.95, 15.  , 15.05, 15.1 , 15.15,
        15.2 , 15.25, 15.3 , 15.35, 15.4 , 15.45],
       [15.5 , 15.55, 15.6 , 15.65, 15.7 , 15.75, 15.8 , 15.85, 15.9 ,
        15.95, 16.  , 16.05, 16.1 , 16.15, 16.2 ],
       [16.25, 16.3 , 16.35, 16.4 , 16.45, 16.5 , 16.55, 16.6 , 16.65,
        16.7 , 16.75, 16.8 , 16.85, 16.9 , 16.95],
       [17.  , 17.05, 17

In [128]:
# arr1.shape = (10,6,3)
# arr1

In [129]:
arr1.shape = (-1,6,3)
arr1

array([[[11.  , 11.05, 11.1 ],
        [11.15, 11.2 , 11.25],
        [11.3 , 11.35, 11.4 ],
        [11.45, 11.5 , 11.55],
        [11.6 , 11.65, 11.7 ],
        [11.75, 11.8 , 11.85]],

       [[11.9 , 11.95, 12.  ],
        [12.05, 12.1 , 12.15],
        [12.2 , 12.25, 12.3 ],
        [12.35, 12.4 , 12.45],
        [12.5 , 12.55, 12.6 ],
        [12.65, 12.7 , 12.75]],

       [[12.8 , 12.85, 12.9 ],
        [12.95, 13.  , 13.05],
        [13.1 , 13.15, 13.2 ],
        [13.25, 13.3 , 13.35],
        [13.4 , 13.45, 13.5 ],
        [13.55, 13.6 , 13.65]],

       [[13.7 , 13.75, 13.8 ],
        [13.85, 13.9 , 13.95],
        [14.  , 14.05, 14.1 ],
        [14.15, 14.2 , 14.25],
        [14.3 , 14.35, 14.4 ],
        [14.45, 14.5 , 14.55]],

       [[14.6 , 14.65, 14.7 ],
        [14.75, 14.8 , 14.85],
        [14.9 , 14.95, 15.  ],
        [15.05, 15.1 , 15.15],
        [15.2 , 15.25, 15.3 ],
        [15.35, 15.4 , 15.45]],

       [[15.5 , 15.55, 15.6 ],
        [15.65, 15.7 , 15.75]

In [ ]:
class Array:
    def __init__(self, shape, size):
        self.shape = shape
        
    def reshape(self, r, c):
        pass

In [138]:
# Transpose of a matrix
arr3 = np.array([[10,11,12,13], [21,22,23,24], [34,35,63,73]])
print(arr3)

[[10 11 12 13]
 [21 22 23 24]
 [34 35 63 73]]


In [139]:
print(arr3.T)

[[10 21 34]
 [11 22 35]
 [12 23 63]
 [13 24 73]]


In [145]:
# arr1 = np.array([[1,2,3,4], [5,6,7,8], [9,8,7,6]]).reshape(4,3)
# arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [8, 7, 6]])

In [146]:
arr1 = np.array([[1,2,3,4], [5,6,7,8], [9,8,7,6]]).reshape((4,3), order = 'F')
# arr1

array([[1, 6, 7],
       [5, 8, 4],
       [9, 3, 8],
       [2, 7, 6]])

In [151]:
a1 = np.arange(7)
a1

array([0, 1, 2, 3, 4, 5, 6])

In [152]:
# C Type representation

a1.reshape((2,4), order = 'C')

ValueError: cannot reshape array of size 7 into shape (2,4)

In [150]:
# Fortran Type representation
a1.reshape((2,4), order = 'F')

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

# Arithmetic Operation on Numpy array

In [153]:
import numpy as np

In [168]:
arr1 = np.array([10,11,12,13,14,15])
arr2 = np.array([20,21,22,23,24,25])

In [156]:
print(arr1 + arr2)

[30 32 34 36 38]


In [158]:
print(arr2 - arr1)

[10 10 10 10 10]


In [159]:
print(arr2/arr1)

[2.         1.90909091 1.83333333 1.76923077 1.71428571]


In [160]:
print(arr2//arr1)

[2 1 1 1 1]


In [161]:
arr2 ** arr1

array([     10240000000000,     350277500542221,   12855002631049216,
        504036361936467383, 2588976049459036160])

In [162]:
arr2 % arr1

array([ 0, 10, 10, 10, 10])

In [164]:
arr2 > 23

array([False, False, False, False,  True])

In [166]:
arr2 < 23

array([ True,  True,  True, False, False])

In [167]:
arr2 * arr1

array([200, 231, 264, 299, 336])

In [171]:
# dot product

# [[10,20],        [[2,3],
# [30,40]]         [4,5]]

# [[100, 130],
# [220, 290]]

arr1 = np.array([[10,20],[30,40]])
arr2 = np.array([[2,3],[4,5]])
print(arr1 * arr2)
print()
print(arr1.dot(arr2))


[[ 20  60]
 [120 200]]

[[100 130]
 [220 290]]


In [ ]:
[[r0c0, r0c1],      [[a0b0, a0b1], 
[r1c0, r1c1]]       [a1b0, a1b1]]


[[(r0c0*a0b0)+(r0c1*a1b0), (r0c0*a0b1)+(r0c1*a1b1)],
[]]