In [3]:
import numpy as np

In [4]:
arr1 = np.array([11,12,13])
arr2 = np.array([21,22,23])

In [5]:
arr1 += 2

# Unary Operations

In [6]:
arr1.sum()

42

In [7]:
arr1.min()

13

In [8]:
arr1.max()

15

In [9]:
arr3 = np.array([[10,11,21,23],[22,24,45,47],[98,76,45,34]])
print(arr3)

[[10 11 21 23]
 [22 24 45 47]
 [98 76 45 34]]


In [10]:
arr3.sum(axis = 0)

array([130, 111, 111, 104])

In [11]:
arr3.sum(axis = 1)

array([ 65, 138, 253])

In [14]:
arr3.max(axis = 0)

array([98, 76, 45, 47])

In [15]:
arr3.max(axis = 1)

array([23, 47, 98])

In [18]:
arr3[:, 1].max()

76

# Universal Functions

In [12]:
np.add(12,13)

25

In [13]:
np.add(arr1,arr2)

array([34, 36, 38])

In [21]:
np.add((10,20,30), (40,50,60))

array([50, 70, 90])

In [22]:
arr4 = np.arange(12).reshape(3,4)
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:

arr5 = np.arange(31, 43).reshape(3,4)
arr5

array([[31, 32, 33, 34],
       [35, 36, 37, 38],
       [39, 40, 41, 42]])

In [29]:
arr3

array([[10, 11, 21, 23],
       [22, 24, 45, 47],
       [98, 76, 45, 34]])

In [30]:
np.add(arr3, arr4)

array([[ 10,  12,  23,  26],
       [ 26,  29,  51,  54],
       [106,  85,  55,  45]])

In [31]:
np.multiply(arr1, arr2)

array([273, 308, 345])

In [32]:
np.multiply(arr3, arr4)

array([[  0,  11,  42,  69],
       [ 88, 120, 270, 329],
       [784, 684, 450, 374]])

In [33]:
np.log(arr1)

array([2.56494936, 2.63905733, 2.7080502 ])

In [34]:
np.log(arr3)

array([[2.30258509, 2.39789527, 3.04452244, 3.13549422],
       [3.09104245, 3.17805383, 3.80666249, 3.8501476 ],
       [4.58496748, 4.33073334, 3.80666249, 3.52636052]])

In [36]:
arr1

array([13, 14, 15])

In [35]:
np.sqrt(arr1)

array([3.60555128, 3.74165739, 3.87298335])

In [37]:
np.square(arr1)

array([169, 196, 225])

# Bitwise Operation


In [38]:
np.bitwise_and(10,20)

0

In [40]:
np.bitwise_and(arr1, arr2)

array([5, 6, 7])

In [41]:
np.bitwise_or(arr1, arr2)

array([29, 30, 31])

In [42]:
np.bitwise_xor(arr1, arr2)

array([24, 24, 24])

In [48]:
eval('0b'+np.binary_repr(23))

23

In [47]:
a = eval('0b10111')
print(a)

23


# Statistical Functions in Numpy

In [60]:
population_data = np.genfromtxt('data/population_2017.csv',usecols=1, 
                         delimiter=',',skip_header=1)

In [59]:
population_data

array([  1618.,   2910.,   4049.,   5177.,   6320.,  11192.,  11359.,
        11773.,  14909.,  17380.,  21729.,  25398.,  31196.,  33400.,
        34571.,  35446.,  37922.,  38695.,  40120.,  49290.,  53127.,
        55144.,  55345.,  55641.,  56480.,  61349.,  61559.,  73925.,
        76965.,  84287.,  94737., 102012., 104901., 105264., 105544.,
       107825., 108020., 109897., 116398., 160539., 164229., 165314.,
       178844., 196440., 204327., 253045., 276244.])

In [64]:
mean = np.mean(population_data)
median = np.median(population_data)
sd = np.std(population_data)
var = np.var(population_data)

In [65]:
print(mean)
print(median)
print(sd)
print(var)

73958.12244897959
55345.0
67180.61487091337
4513235014.433986


# Indexing & Slicing

In [66]:
arr1

array([13, 14, 15])

In [68]:
print(arr1[0])

13


In [69]:
print(arr1[-1])

15


In [70]:
arr1[0] = 100
arr1

array([100,  14,  15])

In [72]:
arr1 = np.array([10,11,12,13,14,15])
arr1

array([10, 11, 12, 13, 14, 15])

In [73]:
arr1[2:4]

array([12, 13])

In [74]:
arr1[::-1]

array([15, 14, 13, 12, 11, 10])

# Indexing in 2D array

In [75]:
arr3

array([[10, 11, 21, 23],
       [22, 24, 45, 47],
       [98, 76, 45, 34]])

In [76]:
arr3[0]

array([10, 11, 21, 23])

In [79]:
arr3[-1]

array([98, 76, 45, 34])

In [84]:
arr3[1,1]

24

In [85]:
arr3[1][1]

24

In [110]:
print(arr3[0:,1])

[11 24 76]


In [104]:
arr3[:,1]

array([11, 24, 76])

In [111]:
arr3

array([[10, 11, 21, 23],
       [22, 24, 45, 47],
       [98, 76, 45, 34]])

In [117]:
arr3

array([[10, 11, 21, 23],
       [22, 24, 45, 47],
       [98, 76, 45, 34]])

In [119]:
col_ind = np.array([0,1,2,1])
col_ind


array([0, 1, 2, 1])

In [121]:
row_ind = np.array([1,2,1,0])
row_ind

array([1, 2, 1, 0])

In [122]:
arr3[row_ind, col_ind]

array([22, 76, 45, 11])

In [123]:
arr6 = np.arange(31, 67).reshape(6,6)
arr6

array([[31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66]])

In [124]:
arr6[0:2, 3]

array([34, 40])

In [125]:
arr6[1,2:4]

array([39, 40])

In [126]:
arr6[3:, 3:]

array([[52, 53, 54],
       [58, 59, 60],
       [64, 65, 66]])

In [127]:
arr6[:,1]

array([32, 38, 44, 50, 56, 62])

In [133]:
arr6

array([[31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66]])

In [129]:
arr6[::2, 2::2]
[31, 32, 33, 34, 35, 36],
[43, 44, 45, 46, 47, 48],
[55, 56, 57, 58, 59, 60],

array([[33, 35],
       [45, 47],
       [57, 59]])

In [132]:
arr6[1]

array([37, 38, 39, 40, 41, 42])

In [137]:
arr6[:, 0].reshape(6,1)

array([[31],
       [37],
       [43],
       [49],
       [55],
       [61]])

In [138]:
arr6

array([[31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66]])

In [139]:
arr7 =arr6[1,0], arr6[2,1], arr6[1,2], arr6[0,1]
arr7

(37, 44, 39, 32)

In [140]:
fruit = np.array([["Banana","Mango","Guava","Avacado"],
            ["Papaya","Jack fruit","Plum","Strawberry"],
            ["Apricot","Apple","Blue berry","Black berry"]])
fruit

array([['Banana', 'Mango', 'Guava', 'Avacado'],
       ['Papaya', 'Jack fruit', 'Plum', 'Strawberry'],
       ['Apricot', 'Apple', 'Blue berry', 'Black berry']], dtype='<U11')

In [142]:
row_ind = np.array([[0,1], [1,2]])
row_ind

array([[0, 1],
       [1, 2]])

In [141]:
col_ind = np.array([[2,1], [3,3]])
col_ind

array([[2, 1],
       [3, 3]])

In [144]:
fruit[row_ind, col_ind] = 'Mango'

In [145]:
fruit

array([['Banana', 'Mango', 'Mango', 'Avacado'],
       ['Papaya', 'Mango', 'Plum', 'Mango'],
       ['Apricot', 'Apple', 'Blue berry', 'Mango']], dtype='<U11')

# Masked array1

In [146]:
arr6

array([[31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66]])

In [148]:
arr6>45

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [149]:
arr6[arr6>45]

array([46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
       63, 64, 65, 66])

In [154]:

# T0 find the sum of all element which are greater than 45 in arr6
np.sum(arr6[arr6>45])

1176

In [155]:
# To find the total number of element which are greater than 45
np.sum(arr6>45)

21

In [156]:
np.sum(arr6>45, axis = 0)

array([3, 3, 3, 4, 4, 4])

In [158]:
np.sum(arr6>45, axis = 1)

array([0, 0, 3, 6, 6, 6])

In [162]:
np.any(arr6>65)

True

In [164]:
np.all(arr6>31)

False

In [167]:
arr6[arr6<45] = 0
arr6

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66]])

# Array with Structured Data


In [183]:
name  = ["Andy","Rosy","Susan","Rick"]

studentID  = [106,102,139,167]

scores = [85.5,90.34,87.65,78.25]

In [172]:
student_data = np.zeros(4, dtype = {'names':('name', 'studentID', 'scores'), 'formats':('U10', 'i4', 'f8')})

In [173]:
student_data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('studentID', '<i4'), ('scores', '<f8')])

In [184]:
student_data['name'] = name
student_data['studentID'] = studentID
student_data['scores'] = scores

In [175]:
student_data

array([('Andy', 106, 85.5 ), ('Rosy', 102, 90.34), ('Susan', 139, 87.65),
       ('Rick', 167, 78.25)],
      dtype=[('name', '<U10'), ('studentID', '<i4'), ('scores', '<f8')])

In [176]:
student_data['name']

array(['Andy', 'Rosy', 'Susan', 'Rick'], dtype='<U10')

In [177]:
student_data['scores']

array([85.5 , 90.34, 87.65, 78.25])

In [178]:
student_data[0]

('Andy', 106, 85.5)

In [180]:
student_data[student_data['scores']>86]['name']

array(['Rosy', 'Susan'], dtype='<U10')